language: c
sudo: false
matrix:
  include:
    - os: linux
      compiler: gcc
      env: TEST=test
    - os: linux
      compiler: clang
      env: TEST=test
    - os: linux
      compiler: gcc
      env: TEST=coverage
    - os: osx
      compiler: clang
      env: TEST=test
script:
  - ./build.sh clean
  - ./build.sh build
  - ./build.sh ${TEST}
  - bash <(curl -s https://codecov.io/bash) -x gcov || echo "Codecov did not collect coverage"
